/* CREATE TABLE IF NOT EXISTS `app_db`.`result` (
  `res` INT NOT NULL,
  `text` VARCHAR(2550) NOT NULL,
  PRIMARY KEY (`id`));

INSERT INTO `app_db`.`result` (`res`, `text`) VALUES ('0', 'Your result is very low, and leaves much to be desired. You only know that you are going to go on a hike, but you do not at all understand why and why. Going anywhere, even in a group, can be deadly for you. For starters, you should go for a picnic in the city park.');
INSERT INTO `app_db`.`result` (`res`, `text`) VALUES ('10', 'Your result is very low, and leaves much to be desired. You only know that you are going to go on a hike, but you do not at all understand why and why. Going anywhere, even in a group, can be deadly for you. For starters, you should go for a picnic in the city park.');
INSERT INTO `app_db`.`result` (`res`, `text`) VALUES ('20', 'Your result is very low, and leaves much to be desired. You only know that you are going to go on a hike, but you do not at all understand why and why. Going anywhere, even in a group, can be deadly for you. For starters, you should go for a picnic in the city park.');
INSERT INTO `app_db`.`result` (`res`, `text`) VALUES ('30', 'Your result is quite low, but not the worst. You are going to go hiking and even know something about it, but this is still too little. You should read the relevant literature, explore the closest hike locations to your place of residence, and hit the road with a group of more experienced people. But don not go far from her.');
INSERT INTO `app_db`.`result` (`res`, `text`) VALUES ('40', 'Your result is quite low, but not the worst. You are going to go hiking and even know something about it, but this is still too little. You should read the relevant literature, explore the closest hike locations to your place of residence, and hit the road with a group of more experienced people. But don not go far from her.');
INSERT INTO `app_db`.`result` (`res`, `text`) VALUES ('50', 'Your result is average, and you can confidently say that you know something about hiking and survival. You can go hiking in the nearby forest or mountains with a group of experienced survivalists, but you should do so during the warmer months. Winter is still too dangerous for you. Gain experience.');
INSERT INTO `app_db`.`result` (`res`, `text`) VALUES ('60', 'Your result is average, and you can confidently say that you know something about hiking and survival. You can go hiking in the nearby forest or mountains with a group of experienced survivalists, but you should do so during the warmer months. Winter is still too dangerous for you. Gain experience.');
INSERT INTO `app_db`.`result` (`res`, `text`) VALUES ('70', 'Your result is good, and you know a lot about hiking and survival. You will know how to light a fire, look for food in the wild and not fall into the clutches of wild animals, but you still have room to grow. Winter in the forest or mountains will not be scary for you if you go on a trip with your friends or companions who have the same experience as you.');
INSERT INTO `app_db`.`result` (`res`, `text`) VALUES ('80', 'Your result is good, and you know a lot about hiking and survival. You will know how to light a fire, look for food in the wild and not fall into the clutches of wild animals, but you still have room to grow. Winter in the forest or mountains will not be scary for you if you go on a trip with your friends or companions who have the same experience as you.');
INSERT INTO `app_db`.`result` (`res`, `text`) VALUES ('90', 'Your result is excellent. You are an experienced survivalist and hiking is your hobby. Survival in the winter forest is nothing for you, and you will successfully return home safe and sound. You are adept at handling fire, foraging in the wild, and handling wild animals. You would make a good guide and leader and guide.');
INSERT INTO `app_db`.`result` (`res`, `text`) VALUES ('100', 'Your result is excellent. You are an experienced survivalist and hiking is your hobby. Survival in the winter forest is nothing for you, and you will successfully return home safe and sound. You are adept at handling fire, foraging in the wild, and handling wild animals. You would make a good guide and leader and guide.'); */
